name: EnvironmentalAudio
main: net.mcbbs.a1mercet.environmentalaudio.EnvironmentalAudio
version: 1.4.1
author: A1MERCet
depend:
  - PlaceholderAPI
softdepend:
  - DragonCore
  - GermPlugin
commands:
  audio:
    aliases:
      - a
      - au
    description: util command
    permission: "audio.cmd"